employeelist=[
    {
        "id":518,
        "name":"Bharath",
        "Company":"wipro",
        "salary":65000
    },
    {
        "id":518,
        "name":"Bharath",
        "Company":"wipro",
        "salary":65000
    },
    {
        "id":518,
        "name":"Bharath",
        "Company":"wipro",
        "salary":65000
    },
    {
        "id":518,
        "name":"Bharath",
        "Company":"wipro",
        "salary":65000
    },
    {
        "id":518,
        "name":"Bharath",
        "Company":"wipro",
        "salary":65000
    },
    {
        "id":518,
        "name":"Bharath",
        "Company":"wipro",
        "salary":65000
    },
    {
        "id":518,
        "name":"Bharath",
        "Company":"wipro",
        "salary":65000
    },
];

function getemployees(){
    return employeelist;
}